### ISSUE TITLE
Allow users to bind to an entire worksheet

### ISSUE THREAD

**Issue by rflprr** [datadotworld/excel-add-in#42]
Users should be able to bind to an entire worksheet, without need to select a specific cell range.
In that case, the add-in needs heuristics to determine which cells to upload to data.world, avoiding empty cells as much as possible.

**Comment by alexzelenak** [comment]
![screenshot 2017-11-21 13 19 12](https://user-images.githubusercontent.com/176824/33092610-4577459e-cec0-11e7-8efc-21325818798b.png)
