### ISSUE TITLE
Revisions to 'Dataset/Add Files' View

### ISSUE THREAD

**Issue by alexzelenak** [datadotworld/excel-add-in#44]
![screenshot 2017-11-17 11 49 20](https://user-images.githubusercontent.com/176824/32961254-758dfa4c-cb8d-11e7-8b81-95c89486607c.png)

**Comment by alexzelenak** [comment]
1. Remove the URL to the project
2. Add a link ('Change linked dataset') back to the 'Select a dataset to link' view (#43)
3. Update the button bar to have (3) buttons instead of 2: 'New File', 'Save', 'View on Web'
4. Update link buttons: Remove the 'Unlink' hover state, remove 'linked' text from button (checkmark only), keep the same gray border around the button in all 3 states (default, linked, saving)
5. Change bottom button text from 'Add data' to 'New file'

**Comment by alevicki** [comment]
@alexzelenak Should there still be a way to unlink the file?

**Comment by alevicki** [comment]
@alexzelenak Your designs seem to have a green border around the checked/linked status but you said 

>  keep the same gray border around the button in all 3 states (default, linked, saving)

which is correct?

**Comment by alexzelenak** [comment]
My bad, there should be a green border in the 'linked/checked' state.
