### ISSUE TITLE
Upload history key should include dataset key and filename

### ISSUE THREAD

**Issue by rflprr** [datadotworld/excel-add-in#78]
Currently, if the user uploads data to different datasets using the same file name, upload history only shows one entry.

Instead, if the filename is the same, but the dataset is different, upload history should display distinct entries.

**Comment by rflprr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Excel: Revamp Sync data](https://trello.com/c/ystG8Uqc/102-excel-revamp-sync-data)

**Comment by kndungu** [comment]
Fixed and merged
